# Generated by Django 4.2.3 on 2023-07-20 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('height', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_level', models.CharField(choices=[('winter', 'winter'), ('summer', 'summer'), ('autumn', 'autumn'), ('spring', 'spring')], default='winter', max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pereval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_pereval', models.CharField(choices=[('Планета Земля', 'Планета Земля'), ('Памиро-Алай', 'Памиро-Алай'), ('Алтай', 'Алтай'), ('Северо-Чуйский хребет', 'Северо-Чуйский хребет'), ('Южно-Чуйский хребет', 'Южно-Чуйский хребет'), ('Катунский хребет', 'Катунский хребет'), ('Фанские горы', 'Фанские горы'), ('Гиссарский хребет (участок западнее перевала Анзоб)', 'Гиссарский хребет (участок западнее перевала Анзоб)'), ('Матчинский горный узел', 'Матчинский горный узел'), ('Горный узел Такали, Туркестанский хребет', 'Горный узел Такали, Туркестанский хребет'), ('Высокий Алай', 'Высокий Алай'), ('Кичик-Алай и Восточный Алай', 'Кичик-Алай и Восточный Алай'), ('Аладаглар', 'Аладаглар'), ('Тавр', 'Тавр'), ('Саяны', 'Саяны'), ('Хребет Листвяга', 'Хребет Листвяга'), ('Ивановский хребет', 'Ивановский хребет'), ('Массив Мунгун-Тайга', 'Массив Мунгун-Тайга'), ('Хребет Цаган-Шибэту', 'Хребет Цаган-Шибэту'), ('Хребет Чихачева (Сайлюгем)', 'Хребет Чихачева (Сайлюгем)'), ('Шапшальский хребет', 'Шапшальский хребет'), ('Хребет Южный Алтай', 'Хребет Южный Алтай'), ('Хребет Монгольский Алтай', 'Хребет Монгольский Алтай'), ('Западный Саян', 'Западный Саян'), ('Восточный Саян', 'Восточный Саян'), ('Кузнецкий Алатау', 'Кузнецкий Алатау'), ('Курайский хребет', 'Курайский хребет')], default='Планета Земля', max_length=60, unique=True)),
                ('status', models.CharField(choices=[('new', 'new'), ('pending', 'pending'), ('accepted', 'accepted'), ('rejected', 'rejected')], default='new', max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='photos/')),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('coords', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Point.coords')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('otchestvo', models.CharField(blank=True, max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PointPereval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pereval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Point.pereval')),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Point.point')),
            ],
        ),
        migrations.CreateModel(
            name='PointLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Point.level')),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Point.point')),
            ],
        ),
        migrations.AddField(
            model_name='point',
            name='level',
            field=models.ManyToManyField(related_name='point', through='Point.PointLevel', to='Point.level'),
        ),
        migrations.AddField(
            model_name='point',
            name='pereval',
            field=models.ManyToManyField(related_name='point', through='Point.PointPereval', to='Point.pereval'),
        ),
        migrations.AddField(
            model_name='point',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Point.users'),
        ),
    ]
