# Generated by Django 4.2.3 on 2023-07-24 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Point', '0002_alter_pereval_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pereval',
            old_name='status',
            new_name='name_status',
        ),
        migrations.AlterField(
            model_name='level',
            name='name_level',
            field=models.CharField(choices=[('winter', 'winter'), ('summer', 'summer'), ('autumn', 'autumn'), ('spring', 'spring')], default='winter', max_length=20),
        ),
        migrations.CreateModel(
            name='PointStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Point.point')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Point.pereval')),
            ],
        ),
        migrations.AddField(
            model_name='point',
            name='status',
            field=models.ManyToManyField(related_name='status', through='Point.PointStatus', to='Point.pereval'),
        ),
    ]
