# Generated by Django 4.2.3 on 2023-07-25 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Point', '0003_rename_status_pereval_name_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_status', models.CharField(choices=[('new', 'new'), ('pending', 'pending'), ('accepted', 'accepted'), ('rejected', 'rejected')], default='new', max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='pereval',
            name='name_status',
        ),
        migrations.AlterField(
            model_name='point',
            name='status',
            field=models.ManyToManyField(related_name='point', through='Point.PointStatus', to='Point.status'),
        ),
        migrations.AlterField(
            model_name='pointstatus',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Point.status'),
        ),
    ]
