# Generated by Django 4.2.4 on 2023-08-09 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Point', '0004_status_remove_pereval_name_status_alter_point_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='point',
            name='status',
            field=models.ManyToManyField(default='new', related_name='point', through='Point.PointStatus', to='Point.status'),
        ),
    ]
