# Generated by Django 4.2.4 on 2023-08-11 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Point', '0005_alter_point_photo_alter_point_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='status',
            field=models.ManyToManyField(related_name='point', through='Point.PointStatus', to='Point.status'),
        ),
    ]
